<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Section 3 Overview | Data Science Inference and Modeling</title>
  <meta name="description" content="4 Section 3 Overview | Data Science Inference and Modeling" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Section 3 Overview | Data Science Inference and Modeling" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Section 3 Overview | Data Science Inference and Modeling" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="section-2-overview.html"/>
<link rel="next" href="section-4-overview.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="learning-objectives.html"><a href="learning-objectives.html"><i class="fa fa-check"></i><b>1</b> Learning Objectives</a>
<ul>
<li class="chapter" data-level="1.1" data-path="learning-objectives.html"><a href="learning-objectives.html#course-overview"><i class="fa fa-check"></i><b>1.1</b> Course Overview</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="learning-objectives.html"><a href="learning-objectives.html#section-1-parameters-and-estimates"><i class="fa fa-check"></i><b>1.1.1</b> Section 1: Parameters and Estimates</a></li>
<li class="chapter" data-level="1.1.2" data-path="learning-objectives.html"><a href="learning-objectives.html#section-2-the-central-limit-theorem-in-practice"><i class="fa fa-check"></i><b>1.1.2</b> Section 2: The Central Limit Theorem in Practice</a></li>
<li class="chapter" data-level="1.1.3" data-path="learning-objectives.html"><a href="learning-objectives.html#section-3-confidence-intervals-and-p-values"><i class="fa fa-check"></i><b>1.1.3</b> Section 3: Confidence Intervals and p-Values</a></li>
<li class="chapter" data-level="1.1.4" data-path="learning-objectives.html"><a href="learning-objectives.html#section-4-statistical-models"><i class="fa fa-check"></i><b>1.1.4</b> Section 4: Statistical Models</a></li>
<li class="chapter" data-level="1.1.5" data-path="learning-objectives.html"><a href="learning-objectives.html#section-5-bayesian-statistics"><i class="fa fa-check"></i><b>1.1.5</b> Section 5: Bayesian Statistics</a></li>
<li class="chapter" data-level="1.1.6" data-path="learning-objectives.html"><a href="learning-objectives.html#section-6-election-forecasting"><i class="fa fa-check"></i><b>1.1.6</b> Section 6: Election Forecasting</a></li>
<li class="chapter" data-level="1.1.7" data-path="learning-objectives.html"><a href="learning-objectives.html#section-7-association-tests"><i class="fa fa-check"></i><b>1.1.7</b> Section 7: Association Tests</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="learning-objectives.html"><a href="learning-objectives.html#introduction-to-inference"><i class="fa fa-check"></i><b>1.2</b> Introduction to Inference</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="section-1-overview.html"><a href="section-1-overview.html"><i class="fa fa-check"></i><b>2</b> Section 1 Overview</a>
<ul>
<li class="chapter" data-level="2.1" data-path="section-1-overview.html"><a href="section-1-overview.html#sampling-model-parameters-and-estimates"><i class="fa fa-check"></i><b>2.1</b> Sampling Model Parameters and Estimates</a></li>
<li class="chapter" data-level="2.2" data-path="section-1-overview.html"><a href="section-1-overview.html#the-sample-average"><i class="fa fa-check"></i><b>2.2</b> The Sample Average</a></li>
<li class="chapter" data-level="2.3" data-path="section-1-overview.html"><a href="section-1-overview.html#polling-versus-forecasting"><i class="fa fa-check"></i><b>2.3</b> Polling versus Forecasting</a></li>
<li class="chapter" data-level="2.4" data-path="section-1-overview.html"><a href="section-1-overview.html#properties-of-our-estimate"><i class="fa fa-check"></i><b>2.4</b> Properties of Our Estimate</a></li>
<li class="chapter" data-level="2.5" data-path="section-1-overview.html"><a href="section-1-overview.html#assessment---parameters-and-estimates"><i class="fa fa-check"></i><b>2.5</b> Assessment - Parameters and Estimates</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="section-2-overview.html"><a href="section-2-overview.html"><i class="fa fa-check"></i><b>3</b> Section 2 Overview</a>
<ul>
<li class="chapter" data-level="3.1" data-path="section-2-overview.html"><a href="section-2-overview.html#the-central-limit-theorem-in-practice"><i class="fa fa-check"></i><b>3.1</b> The Central Limit Theorem in Practice</a></li>
<li class="chapter" data-level="3.2" data-path="section-2-overview.html"><a href="section-2-overview.html#margin-of-error"><i class="fa fa-check"></i><b>3.2</b> Margin of Error</a></li>
<li class="chapter" data-level="3.3" data-path="section-2-overview.html"><a href="section-2-overview.html#a-monte-carlo-simulation-for-the-clt"><i class="fa fa-check"></i><b>3.3</b> A Monte Carlo Simulation for the CLT</a></li>
<li class="chapter" data-level="3.4" data-path="section-2-overview.html"><a href="section-2-overview.html#the-spread"><i class="fa fa-check"></i><b>3.4</b> The Spread</a></li>
<li class="chapter" data-level="3.5" data-path="section-2-overview.html"><a href="section-2-overview.html#bias-why-not-run-a-very-large-poll"><i class="fa fa-check"></i><b>3.5</b> Bias: Why Not Run a Very Large Poll?</a></li>
<li class="chapter" data-level="3.6" data-path="section-2-overview.html"><a href="section-2-overview.html#assessment---introduction-to-inference"><i class="fa fa-check"></i><b>3.6</b> Assessment - Introduction to Inference</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="section-3-overview.html"><a href="section-3-overview.html"><i class="fa fa-check"></i><b>4</b> Section 3 Overview</a>
<ul>
<li class="chapter" data-level="4.1" data-path="section-3-overview.html"><a href="section-3-overview.html#confidence-intervals"><i class="fa fa-check"></i><b>4.1</b> Confidence Intervals</a></li>
<li class="chapter" data-level="4.2" data-path="section-3-overview.html"><a href="section-3-overview.html#a-monte-carlo-simulation-for-confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> A Monte Carlo Simulation for Confidence Intervals</a></li>
<li class="chapter" data-level="4.3" data-path="section-3-overview.html"><a href="section-3-overview.html#the-correct-language"><i class="fa fa-check"></i><b>4.3</b> The Correct Language</a></li>
<li class="chapter" data-level="4.4" data-path="section-3-overview.html"><a href="section-3-overview.html#power"><i class="fa fa-check"></i><b>4.4</b> Power</a></li>
<li class="chapter" data-level="4.5" data-path="section-3-overview.html"><a href="section-3-overview.html#p-values"><i class="fa fa-check"></i><b>4.5</b> p-Values</a></li>
<li class="chapter" data-level="4.6" data-path="section-3-overview.html"><a href="section-3-overview.html#another-explanation-of-p-values"><i class="fa fa-check"></i><b>4.6</b> Another Explanation of p-Values</a></li>
<li class="chapter" data-level="4.7" data-path="section-3-overview.html"><a href="section-3-overview.html#assessment---confidence-intervals-and-p-values"><i class="fa fa-check"></i><b>4.7</b> Assessment - Confidence Intervals and p-Values</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="section-4-overview.html"><a href="section-4-overview.html"><i class="fa fa-check"></i><b>5</b> Section 4 Overview</a>
<ul>
<li class="chapter" data-level="5.1" data-path="section-4-overview.html"><a href="section-4-overview.html#poll-aggregators"><i class="fa fa-check"></i><b>5.1</b> Poll Aggregators</a></li>
<li class="chapter" data-level="5.2" data-path="section-4-overview.html"><a href="section-4-overview.html#pollsters-and-multilevel-models"><i class="fa fa-check"></i><b>5.2</b> Pollsters and Multilevel Models</a></li>
<li class="chapter" data-level="5.3" data-path="section-4-overview.html"><a href="section-4-overview.html#poll-data-and-pollster-bias"><i class="fa fa-check"></i><b>5.3</b> Poll Data and Pollster Bias</a></li>
<li class="chapter" data-level="5.4" data-path="section-4-overview.html"><a href="section-4-overview.html#data-driven-models"><i class="fa fa-check"></i><b>5.4</b> Data-Driven Models</a></li>
<li class="chapter" data-level="5.5" data-path="section-4-overview.html"><a href="section-4-overview.html#assessment---statistical-models"><i class="fa fa-check"></i><b>5.5</b> Assessment - Statistical Models</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="section-5-overview.html"><a href="section-5-overview.html"><i class="fa fa-check"></i><b>6</b> Section 5 Overview</a>
<ul>
<li class="chapter" data-level="6.1" data-path="section-5-overview.html"><a href="section-5-overview.html#bayesian-statistics"><i class="fa fa-check"></i><b>6.1</b> Bayesian Statistics</a></li>
<li class="chapter" data-level="6.2" data-path="section-5-overview.html"><a href="section-5-overview.html#bayes-theorem"><i class="fa fa-check"></i><b>6.2</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="6.3" data-path="section-5-overview.html"><a href="section-5-overview.html#bayes-in-practice"><i class="fa fa-check"></i><b>6.3</b> Bayes in Practice</a></li>
<li class="chapter" data-level="6.4" data-path="section-5-overview.html"><a href="section-5-overview.html#the-hierarchical-model"><i class="fa fa-check"></i><b>6.4</b> The Hierarchical Model</a></li>
<li class="chapter" data-level="6.5" data-path="section-5-overview.html"><a href="section-5-overview.html#assessment---bayesian-statistics"><i class="fa fa-check"></i><b>6.5</b> Assessment - Bayesian Statistics</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="section-6-overview.html"><a href="section-6-overview.html"><i class="fa fa-check"></i><b>7</b> Section 6 Overview</a>
<ul>
<li class="chapter" data-level="7.1" data-path="section-6-overview.html"><a href="section-6-overview.html#election-forecasting"><i class="fa fa-check"></i><b>7.1</b> Election Forecasting</a></li>
<li class="chapter" data-level="7.2" data-path="section-6-overview.html"><a href="section-6-overview.html#mathematical-representations-of-models"><i class="fa fa-check"></i><b>7.2</b> Mathematical Representations of Models</a></li>
<li class="chapter" data-level="7.3" data-path="section-6-overview.html"><a href="section-6-overview.html#predicting-the-electoral-college"><i class="fa fa-check"></i><b>7.3</b> Predicting the Electoral College</a></li>
<li class="chapter" data-level="7.4" data-path="section-6-overview.html"><a href="section-6-overview.html#forecasting"><i class="fa fa-check"></i><b>7.4</b> Forecasting</a></li>
<li class="chapter" data-level="7.5" data-path="section-6-overview.html"><a href="section-6-overview.html#assessment---election-forecasting"><i class="fa fa-check"></i><b>7.5</b> Assessment - Election Forecasting</a></li>
<li class="chapter" data-level="7.6" data-path="section-6-overview.html"><a href="section-6-overview.html#the-t-distribution"><i class="fa fa-check"></i><b>7.6</b> The t-Distribution</a></li>
<li class="chapter" data-level="7.7" data-path="section-6-overview.html"><a href="section-6-overview.html#assessment---the-t-distribution"><i class="fa fa-check"></i><b>7.7</b> Assessment - The t-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="section-7-overview.html"><a href="section-7-overview.html"><i class="fa fa-check"></i><b>8</b> Section 7 Overview</a>
<ul>
<li class="chapter" data-level="8.1" data-path="section-7-overview.html"><a href="section-7-overview.html#association-tests"><i class="fa fa-check"></i><b>8.1</b> Association Tests</a></li>
<li class="chapter" data-level="8.2" data-path="section-7-overview.html"><a href="section-7-overview.html#chi-squared-tests"><i class="fa fa-check"></i><b>8.2</b> Chi-Squared Tests</a></li>
<li class="chapter" data-level="8.3" data-path="section-7-overview.html"><a href="section-7-overview.html#assessment---association-and-chi-squared-tests"><i class="fa fa-check"></i><b>8.3</b> Assessment - Association and Chi-Squared Tests</a></li>
<li class="chapter" data-level="8.4" data-path="section-7-overview.html"><a href="section-7-overview.html#comprehensive-assessment-brexit"><i class="fa fa-check"></i><b>8.4</b> Comprehensive Assessment: Brexit</a></li>
<li class="chapter" data-level="8.5" data-path="section-7-overview.html"><a href="section-7-overview.html#brexit-poll-analysis---part-1"><i class="fa fa-check"></i><b>8.5</b> Brexit poll analysis - Part 1</a></li>
<li class="chapter" data-level="8.6" data-path="section-7-overview.html"><a href="section-7-overview.html#brexit-poll-analysis---part-2"><i class="fa fa-check"></i><b>8.6</b> Brexit poll analysis - Part 2</a></li>
<li class="chapter" data-level="8.7" data-path="section-7-overview.html"><a href="section-7-overview.html#brexit-poll-analysis---part-3"><i class="fa fa-check"></i><b>8.7</b> Brexit poll analysis - Part 3</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science Inference and Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-3-overview" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Section 3 Overview</h1>
<p>In Section 3, you will look at confidence intervals and p-values.</p>
<p>After completing Section 3, you will be able to:</p>
<ul>
<li>Calculate confidence intervals of difference sizes around an estimate.</li>
<li>Understand that a confidence interval is a random interval with the given probability of falling on top of the parameter.</li>
<li>Explain the concept of “power” as it relates to inference.</li>
<li>Understand the relationship between p-values and confidence intervals and explain why reporting confidence intervals is often preferable.</li>
</ul>
<div id="confidence-intervals" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Confidence Intervals</h2>
<p>The textbook for this section is available <a href="https://rafalab.github.io/dsbook/inference.html#confidence-intervals" target="_blank">here</a>.</p>
<p><strong>Key points</strong></p>
<ul>
<li>We can use statistical theory to compute the probability that a given interval contains the true parameter <span class="math inline">\(p\)</span>.</li>
<li>95% confidence intervals are intervals constructed to have a 95% chance of including <span class="math inline">\(p\)</span>. The margin of error is approximately a 95% confidence interval.</li>
<li>The start and end of these confidence intervals are random variables.</li>
<li>To calculate any size confidence interval, we need to calculate the value <span class="math inline">\(z\)</span> for which <span class="math inline">\(\mbox{Pr}(-z \le Z \le z)\)</span> equals the desired confidence. For example, a 99% confidence interval requires calculating <span class="math inline">\(z\)</span> for <span class="math inline">\(\mbox{Pr}(-z \le Z \le z) = 0.99\)</span>.</li>
<li>For a confidence interval of size <span class="math inline">\(q\)</span>, we solve for <span class="math inline">\(z = 1 - \frac{1 - q}{2}\)</span>.</li>
<li>To determine a 95% confidence interval, use <code>z &lt;- qnorm(0.975)</code>. This value is slightly smaller than 2 times the standard error.</li>
</ul>
<p><em>Code: geom_smooth confidence interval example</em></p>
<p>The shaded area around the curve is related to the concept of confidence intervals.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="section-3-overview.html#cb41-1" aria-hidden="true"></a><span class="kw">data</span>(<span class="st">&quot;nhtemp&quot;</span>)</span>
<span id="cb41-2"><a href="section-3-overview.html#cb41-2" aria-hidden="true"></a><span class="kw">data.frame</span>(<span class="dt">year =</span> <span class="kw">as.numeric</span>(<span class="kw">time</span>(nhtemp)), <span class="dt">temperature =</span> <span class="kw">as.numeric</span>(nhtemp)) <span class="op">%&gt;%</span></span>
<span id="cb41-3"><a href="section-3-overview.html#cb41-3" aria-hidden="true"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(year, temperature)) <span class="op">+</span></span>
<span id="cb41-4"><a href="section-3-overview.html#cb41-4" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb41-5"><a href="section-3-overview.html#cb41-5" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_smooth</span>() <span class="op">+</span></span>
<span id="cb41-6"><a href="section-3-overview.html#cb41-6" aria-hidden="true"></a><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Average Yearly Temperatures in New Haven&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="img/figures/unnamed-chunk-19-1.png" width="672" /></p>
<p><em>Code: Monte Carlo simulation of confidence intervals</em></p>
<p>Note that to compute the exact 95% confidence interval, we would use <code>qnorm(.975)*SE_hat</code> instead of <code>2*SE_hat</code>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="section-3-overview.html#cb43-1" aria-hidden="true"></a>p &lt;-<span class="st"> </span><span class="fl">0.45</span></span>
<span id="cb43-2"><a href="section-3-overview.html#cb43-2" aria-hidden="true"></a>N &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb43-3"><a href="section-3-overview.html#cb43-3" aria-hidden="true"></a>X &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">size =</span> N, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">prob =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">-</span>p, p))    <span class="co"># generate N observations</span></span>
<span id="cb43-4"><a href="section-3-overview.html#cb43-4" aria-hidden="true"></a>X_hat &lt;-<span class="st"> </span><span class="kw">mean</span>(X)    <span class="co"># calculate X_hat</span></span>
<span id="cb43-5"><a href="section-3-overview.html#cb43-5" aria-hidden="true"></a>SE_hat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>N)    <span class="co"># calculate SE_hat, SE of the mean of N observations</span></span>
<span id="cb43-6"><a href="section-3-overview.html#cb43-6" aria-hidden="true"></a><span class="kw">c</span>(X_hat <span class="op">-</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>SE_hat, X_hat <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>SE_hat)    <span class="co"># build interval of 2*SE above and below mean</span></span></code></pre></div>
<pre><code>## [1] 0.4135691 0.4764309</code></pre>
<p><em>Code: Solving for <span class="math inline">\(z\)</span> with <code>qnorm</code></em></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="section-3-overview.html#cb45-1" aria-hidden="true"></a>z &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.995</span>)    <span class="co"># calculate z to solve for 99% confidence interval</span></span>
<span id="cb45-2"><a href="section-3-overview.html#cb45-2" aria-hidden="true"></a><span class="kw">pnorm</span>(<span class="kw">qnorm</span>(<span class="fl">0.995</span>))    <span class="co"># demonstrating that qnorm gives the z value for a given probability</span></span></code></pre></div>
<pre><code>## [1] 0.995</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="section-3-overview.html#cb47-1" aria-hidden="true"></a><span class="kw">pnorm</span>(<span class="kw">qnorm</span>(<span class="dv">1</span><span class="fl">-0.995</span>))    <span class="co"># demonstrating symmetry of 1-qnorm</span></span></code></pre></div>
<pre><code>## [1] 0.005</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="section-3-overview.html#cb49-1" aria-hidden="true"></a><span class="kw">pnorm</span>(z) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>z)    <span class="co"># demonstrating that this z value gives correct probability for interval</span></span></code></pre></div>
<pre><code>## [1] 0.99</code></pre>
</div>
<div id="a-monte-carlo-simulation-for-confidence-intervals" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> A Monte Carlo Simulation for Confidence Intervals</h2>
<p>The textbook for this section is available <a href="https://rafalab.github.io/dsbook/inference.html#a-monte-carlo-simulation-1" target="_blank">here</a>.</p>
<p><strong>Key points</strong></p>
<ul>
<li>We can run a Monte Carlo simulation to confirm that a 95% confidence interval contains the true value of <span class="math inline">\(p\)</span> 95% of the time.</li>
<li>A plot of confidence intervals from this simulation demonstrates that most intervals include <span class="math inline">\(p\)</span>, but roughly 5% of intervals miss the true value of <span class="math inline">\(p\)</span>.</li>
</ul>
<p><em>Code: Monte Carlo simulation</em></p>
<p>Note that to compute the exact 95% confidence interval, we would use <code>qnorm(.975)*SE_hat</code> instead of <code>2*SE_hat</code>.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="section-3-overview.html#cb51-1" aria-hidden="true"></a>B &lt;-<span class="st"> </span><span class="dv">10000</span></span>
<span id="cb51-2"><a href="section-3-overview.html#cb51-2" aria-hidden="true"></a>inside &lt;-<span class="st"> </span><span class="kw">replicate</span>(B, {</span>
<span id="cb51-3"><a href="section-3-overview.html#cb51-3" aria-hidden="true"></a>    X &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">size =</span> N, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">prob =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">-</span>p, p))</span>
<span id="cb51-4"><a href="section-3-overview.html#cb51-4" aria-hidden="true"></a>    X_hat &lt;-<span class="st"> </span><span class="kw">mean</span>(X)</span>
<span id="cb51-5"><a href="section-3-overview.html#cb51-5" aria-hidden="true"></a>    SE_hat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>N)</span>
<span id="cb51-6"><a href="section-3-overview.html#cb51-6" aria-hidden="true"></a>    <span class="kw">between</span>(p, X_hat <span class="op">-</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>SE_hat, X_hat <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>SE_hat)    <span class="co"># TRUE if p in confidence interval</span></span>
<span id="cb51-7"><a href="section-3-overview.html#cb51-7" aria-hidden="true"></a>})</span>
<span id="cb51-8"><a href="section-3-overview.html#cb51-8" aria-hidden="true"></a><span class="kw">mean</span>(inside)</span></code></pre></div>
<pre><code>## [1] 0.9566</code></pre>
</div>
<div id="the-correct-language" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> The Correct Language</h2>
<p>The textbook for this section is available <a href="https://rafalab.github.io/dsbook/inference.html#the-correct-language" target="_blank">here</a>.</p>
<p><strong>Key points</strong></p>
<ul>
<li>The 95% confidence intervals are random, but <span class="math inline">\(p\)</span> is not random.</li>
<li>95% refers to the probability that the random interval falls on top of <span class="math inline">\(p\)</span>.</li>
<li>It is technically incorrect to state that <span class="math inline">\(p\)</span> has a 95% chance of being in between two values because that implies <span class="math inline">\(p\)</span> is random.</li>
</ul>
</div>
<div id="power" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Power</h2>
<p>The textbook for this section is available <a href="https://rafalab.github.io/dsbook/inference.html#power" target="_blank">here</a>.</p>
<p><strong>Key points</strong></p>
<ul>
<li>If we are trying to predict the result of an election, then a confidence interval that includes a spread of 0 (a tie) is not helpful.</li>
<li>A confidence interval that includes a spread of 0 does not imply a close election, it means the sample size is too small.</li>
<li>Power is the probability of detecting an effect when there is a true effect to find. Power increases as sample size increases, because larger sample size means smaller standard error.</li>
</ul>
<p><em>Code: Confidence interval for the spread with sample size of 25</em></p>
<p>Note that to compute the exact 95% confidence interval, we would use <code>c(-qnorm(.975), qnorm(.975))</code> instead of 1.96.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="section-3-overview.html#cb53-1" aria-hidden="true"></a>N &lt;-<span class="st"> </span><span class="dv">25</span></span>
<span id="cb53-2"><a href="section-3-overview.html#cb53-2" aria-hidden="true"></a>X_hat &lt;-<span class="st"> </span><span class="fl">0.48</span></span>
<span id="cb53-3"><a href="section-3-overview.html#cb53-3" aria-hidden="true"></a>(<span class="dv">2</span><span class="op">*</span>X_hat <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>)<span class="op">*</span><span class="dv">2</span><span class="op">*</span><span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>N)</span></code></pre></div>
<pre><code>## [1] -0.4396799  0.3596799</code></pre>
</div>
<div id="p-values" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> p-Values</h2>
<p>The textbook for this section is available <a href="https://rafalab.github.io/dsbook/inference.html#p-values" target="_blank">here</a>.</p>
<p><strong>Key points</strong></p>
<ul>
<li>The null hypothesis is the hypothesis that there is no effect. In this case, the null hypothesis is that the spread is 0, or <span class="math inline">\(p = 0.5\)</span>.</li>
<li>The p-value is the probability of detecting an effect of a certain size or larger when the null hypothesis is true.</li>
<li>We can convert the probability of seeing an observed value under the null hypothesis into a standard normal random variable. We compute the value of <span class="math inline">\(z\)</span> that corresponds to the observed result, and then use that <span class="math inline">\(z\)</span> to compute the p-value.</li>
<li>If a 95% confidence interval does not include our observed value, then the p-value must be smaller than 0.05.</li>
<li>It is preferable to report confidence intervals instead of p-values, as confidence intervals give information about the size of the estimate and p-values do not.</li>
</ul>
<p><em>Code: Computing a p-value for observed spread of 0.02</em></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="section-3-overview.html#cb55-1" aria-hidden="true"></a>N &lt;-<span class="st"> </span><span class="dv">100</span>    <span class="co"># sample size</span></span>
<span id="cb55-2"><a href="section-3-overview.html#cb55-2" aria-hidden="true"></a>z &lt;-<span class="st"> </span><span class="kw">sqrt</span>(N) <span class="op">*</span><span class="st"> </span><span class="fl">0.02</span><span class="op">/</span><span class="fl">0.5</span>    <span class="co"># spread of 0.02</span></span>
<span id="cb55-3"><a href="section-3-overview.html#cb55-3" aria-hidden="true"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(<span class="kw">pnorm</span>(z) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>z))</span></code></pre></div>
<pre><code>## [1] 0.6891565</code></pre>
</div>
<div id="another-explanation-of-p-values" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Another Explanation of p-Values</h2>
<p>The p-value is the probability of observing a value as extreme or more extreme than the result given that the null hypothesis is true.</p>
<p>In the context of the normal distribution, this refers to the probability of observing a Z-score whose absolute value is as high or higher than the Z-score of interest.</p>
<p>Suppose we want to find the p-value of an observation 2 standard deviations larger than the mean. This means we are looking for anything with <span class="math inline">\(|z| \ge 2\)</span>.</p>
<p>Graphically, the p-value gives the probability of an observation that’s at least as far away from the mean or further. This plot shows a standard normal distribution (centered at <span class="math inline">\(z = 0\)</span>) with a standard deviation of 1). The shaded tails are the region of the graph that are 2 standard deviations or more away from the mean.</p>
<div class="figure">
<img src="images/normal_distribution.jpg" alt="" />
<p class="caption">Standard normal distribution (centered at z=0 with a standard deviation of 1</p>
</div>
<p>The p-value is the proportion of area under a normal curve that has z-scores as extreme or more extreme than the given value - the tails on this plot of a normal distribution are shaded to show the region corresponding to the p-value.</p>
<p>The right tail can be found with <code>1-pnorm(2)</code>. We want to have both tails, though, because we want to find the probability of any observation as far away from the mean or farther, in either direction. (This is what’s meant by a two-tailed p-value.) Because the distribution is symmetrical, the right and left tails are the same size and we know that our desired value is just <code>2*(1-pnorm(2))</code>.</p>
<p>Recall that, by default, <code>pnorm()</code> gives the CDF for a normal distribution with a mean of <span class="math inline">\(\mu = 0\)</span> and standard deviation of <span class="math inline">\(\sigma = 1\)</span>. To find p-values for a given z-score z in a normal distribution with mean <code>mu</code> and standard deviation <code>sigma</code>, use <code>2*(1-pnorm(z, mu, sigma))</code> instead.</p>
</div>
<div id="assessment---confidence-intervals-and-p-values" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Assessment - Confidence Intervals and p-Values</h2>
<ol style="list-style-type: decimal">
<li>For the following exercises, we will use actual poll data from the 2016 election.</li>
</ol>
<p>The exercises will contain pre-loaded data from the <code>dslabs</code> package.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="section-3-overview.html#cb57-1" aria-hidden="true"></a><span class="kw">library</span>(dslabs)</span>
<span id="cb57-2"><a href="section-3-overview.html#cb57-2" aria-hidden="true"></a><span class="kw">data</span>(<span class="st">&quot;polls_us_election_2016&quot;</span>)</span></code></pre></div>
<p>We will use all the national polls that ended within a few weeks before the election.</p>
<p>Assume there are only two candidates and construct a 95% confidence interval for the election night proportion <span class="math inline">\(p\)</span>.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="section-3-overview.html#cb58-1" aria-hidden="true"></a><span class="co"># Load the data</span></span>
<span id="cb58-2"><a href="section-3-overview.html#cb58-2" aria-hidden="true"></a><span class="kw">data</span>(polls_us_election_<span class="dv">2016</span>)</span>
<span id="cb58-3"><a href="section-3-overview.html#cb58-3" aria-hidden="true"></a></span>
<span id="cb58-4"><a href="section-3-overview.html#cb58-4" aria-hidden="true"></a><span class="co"># Generate an object `polls` that contains data filtered for polls that ended on or after October 31, 2016 in the United States</span></span>
<span id="cb58-5"><a href="section-3-overview.html#cb58-5" aria-hidden="true"></a>polls &lt;-<span class="st"> </span><span class="kw">filter</span>(polls_us_election_<span class="dv">2016</span>, enddate <span class="op">&gt;=</span><span class="st"> &quot;2016-10-31&quot;</span> <span class="op">&amp;</span><span class="st"> </span>state <span class="op">==</span><span class="st"> &quot;U.S.&quot;</span>)</span>
<span id="cb58-6"><a href="section-3-overview.html#cb58-6" aria-hidden="true"></a></span>
<span id="cb58-7"><a href="section-3-overview.html#cb58-7" aria-hidden="true"></a><span class="co"># How many rows does `polls` contain? Print this value to the console.</span></span>
<span id="cb58-8"><a href="section-3-overview.html#cb58-8" aria-hidden="true"></a><span class="kw">nrow</span>(polls)</span></code></pre></div>
<pre><code>## [1] 70</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="section-3-overview.html#cb60-1" aria-hidden="true"></a><span class="co"># Assign the sample size of the first poll in `polls` to a variable called `N`. Print this value to the console.</span></span>
<span id="cb60-2"><a href="section-3-overview.html#cb60-2" aria-hidden="true"></a>N &lt;-<span class="st"> </span><span class="kw">head</span>(polls<span class="op">$</span>samplesize,<span class="dv">1</span>)</span>
<span id="cb60-3"><a href="section-3-overview.html#cb60-3" aria-hidden="true"></a>N</span></code></pre></div>
<pre><code>## [1] 2220</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="section-3-overview.html#cb62-1" aria-hidden="true"></a><span class="co"># For the first poll in `polls`, assign the estimated percentage of Clinton voters to a variable called `X_hat`. Print this value to the console.</span></span>
<span id="cb62-2"><a href="section-3-overview.html#cb62-2" aria-hidden="true"></a>X_hat &lt;-<span class="st"> </span>(<span class="kw">head</span>(polls<span class="op">$</span>rawpoll_clinton,<span class="dv">1</span>)<span class="op">/</span><span class="dv">100</span>)</span>
<span id="cb62-3"><a href="section-3-overview.html#cb62-3" aria-hidden="true"></a>X_hat</span></code></pre></div>
<pre><code>## [1] 0.47</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="section-3-overview.html#cb64-1" aria-hidden="true"></a><span class="co"># Calculate the standard error of `X_hat` and save it to a variable called `se_hat`. Print this value to the console.</span></span>
<span id="cb64-2"><a href="section-3-overview.html#cb64-2" aria-hidden="true"></a>se_hat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>N)</span>
<span id="cb64-3"><a href="section-3-overview.html#cb64-3" aria-hidden="true"></a>se_hat</span></code></pre></div>
<pre><code>## [1] 0.01059279</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="section-3-overview.html#cb66-1" aria-hidden="true"></a><span class="co"># Use `qnorm` to calculate the 95% confidence interval for the proportion of Clinton voters. Save the lower and then the upper confidence interval to a variable called `ci`.</span></span>
<span id="cb66-2"><a href="section-3-overview.html#cb66-2" aria-hidden="true"></a>ci &lt;-<span class="st"> </span><span class="kw">c</span>(X_hat <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat, X_hat <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat)</span>
<span id="cb66-3"><a href="section-3-overview.html#cb66-3" aria-hidden="true"></a>ci</span></code></pre></div>
<pre><code>## [1] 0.4492385 0.4907615</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Create a new object called <code>pollster_results</code> that contains the pollster’s name, the end date of the poll, the proportion of voters who declared a vote for Clinton, the standard error of this estimate, and the lower and upper bounds of the confidence interval for the estimate.</li>
</ol>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="section-3-overview.html#cb68-1" aria-hidden="true"></a><span class="co"># The `polls` object that filtered all the data by date and nation has already been loaded. Examine it using the `head` function.</span></span>
<span id="cb68-2"><a href="section-3-overview.html#cb68-2" aria-hidden="true"></a><span class="kw">head</span>(polls)</span></code></pre></div>
<pre><code>##   state  startdate    enddate                                                   pollster grade samplesize population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin
## 1  U.S. 2016-11-03 2016-11-06                                   ABC News/Washington Post    A+       2220         lv           47.00         43.00            4.00               NA
## 2  U.S. 2016-11-01 2016-11-07                                    Google Consumer Surveys     B      26574         lv           38.03         35.69            5.46               NA
## 3  U.S. 2016-11-02 2016-11-06                                                      Ipsos    A-       2195         lv           42.00         39.00            6.00               NA
## 4  U.S. 2016-11-04 2016-11-07                                                     YouGov     B       3677         lv           45.00         41.00            5.00               NA
## 5  U.S. 2016-11-03 2016-11-06                                           Gravis Marketing    B-      16639         rv           47.00         43.00            3.00               NA
## 6  U.S. 2016-11-03 2016-11-06 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1295         lv           48.00         44.00            3.00               NA
##   adjpoll_clinton adjpoll_trump adjpoll_johnson adjpoll_mcmullin
## 1        45.20163      41.72430        4.626221               NA
## 2        43.34557      41.21439        5.175792               NA
## 3        42.02638      38.81620        6.844734               NA
## 4        45.65676      40.92004        6.069454               NA
## 5        46.84089      42.33184        3.726098               NA
## 6        49.02208      43.95631        3.057876               NA</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="section-3-overview.html#cb70-1" aria-hidden="true"></a><span class="co"># Create a new object called `pollster_results` that contains columns for pollster name, end date, X_hat, se_hat, lower confidence interval, and upper confidence interval for each poll.</span></span>
<span id="cb70-2"><a href="section-3-overview.html#cb70-2" aria-hidden="true"></a>polls &lt;-<span class="st"> </span><span class="kw">mutate</span>(polls, <span class="dt">X_hat =</span> polls<span class="op">$</span>rawpoll_clinton<span class="op">/</span><span class="dv">100</span>, <span class="dt">se_hat =</span> <span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>polls<span class="op">$</span>samplesize), <span class="dt">lower =</span> X_hat <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat, <span class="dt">upper =</span> X_hat <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat)</span>
<span id="cb70-3"><a href="section-3-overview.html#cb70-3" aria-hidden="true"></a>pollster_results &lt;-<span class="st"> </span><span class="kw">select</span>(polls, pollster, enddate, X_hat, se_hat, lower, upper)</span>
<span id="cb70-4"><a href="section-3-overview.html#cb70-4" aria-hidden="true"></a>pollster_results</span></code></pre></div>
<pre><code>##                                                      pollster    enddate  X_hat      se_hat     lower     upper
## 1                                    ABC News/Washington Post 2016-11-06 0.4700 0.010592790 0.4492385 0.4907615
## 2                                     Google Consumer Surveys 2016-11-07 0.3803 0.002978005 0.3744632 0.3861368
## 3                                                       Ipsos 2016-11-06 0.4200 0.010534681 0.3993524 0.4406476
## 4                                                      YouGov 2016-11-07 0.4500 0.008204286 0.4339199 0.4660801
## 5                                            Gravis Marketing 2016-11-06 0.4700 0.003869218 0.4624165 0.4775835
## 6  Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-06 0.4800 0.013883131 0.4527896 0.5072104
## 7                                     CBS News/New York Times 2016-11-06 0.4500 0.013174309 0.4241788 0.4758212
## 8                                NBC News/Wall Street Journal 2016-11-05 0.4400 0.013863610 0.4128278 0.4671722
## 9                                                    IBD/TIPP 2016-11-07 0.4120 0.014793245 0.3830058 0.4409942
## 10                                           Selzer &amp; Company 2016-11-06 0.4400 0.017560908 0.4055813 0.4744187
## 11                                          Angus Reid Global 2016-11-04 0.4800 0.014725994 0.4511376 0.5088624
## 12                                        Monmouth University 2016-11-06 0.5000 0.018281811 0.4641683 0.5358317
## 13                                             Marist College 2016-11-03 0.4400 0.016190357 0.4082675 0.4717325
## 14                                   The Times-Picayune/Lucid 2016-11-07 0.4500 0.009908346 0.4305800 0.4694200
## 15                                      USC Dornsife/LA Times 2016-11-07 0.4361 0.009096403 0.4182714 0.4539286
## 16                      RKM Research and Communications, Inc. 2016-11-05 0.4760 0.015722570 0.4451843 0.5068157
## 17                                       CVOTER International 2016-11-06 0.4891 0.012400526 0.4647954 0.5134046
## 18                                            Morning Consult 2016-11-05 0.4500 0.012923005 0.4246714 0.4753286
## 19                                               SurveyMonkey 2016-11-06 0.4700 0.001883809 0.4663078 0.4736922
## 20                   Rasmussen Reports/Pulse Opinion Research 2016-11-06 0.4500 0.012845233 0.4248238 0.4751762
## 21                                              Insights West 2016-11-07 0.4900 0.016304940 0.4580429 0.5219571
## 22                                 RAND (American Life Panel) 2016-11-01 0.4370 0.010413043 0.4165908 0.4574092
## 23 Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-03 0.4550 0.014966841 0.4256655 0.4843345
## 24                                    CBS News/New York Times 2016-11-01 0.4500 0.016339838 0.4179745 0.4820255
## 25                                   ABC News/Washington Post 2016-11-05 0.4700 0.011340235 0.4477735 0.4922265
## 26                                                      Ipsos 2016-11-04 0.4300 0.010451057 0.4095163 0.4504837
## 27                                   ABC News/Washington Post 2016-11-04 0.4800 0.012170890 0.4561455 0.5038545
## 28                                                     YouGov 2016-11-06 0.4290 0.001704722 0.4256588 0.4323412
## 29                                                   IBD/TIPP 2016-11-06 0.4070 0.015337369 0.3769393 0.4370607
## 30                                   ABC News/Washington Post 2016-11-03 0.4700 0.013249383 0.4440317 0.4959683
## 31                                                   IBD/TIPP 2016-11-03 0.4440 0.016580236 0.4115033 0.4764967
## 32                                                   IBD/TIPP 2016-11-05 0.4300 0.016475089 0.3977094 0.4622906
## 33                                   ABC News/Washington Post 2016-11-02 0.4700 0.014711237 0.4411665 0.4988335
## 34                                   ABC News/Washington Post 2016-11-01 0.4700 0.014610041 0.4413648 0.4986352
## 35                                   ABC News/Washington Post 2016-10-31 0.4600 0.014496630 0.4315871 0.4884129
## 36                                                      Ipsos 2016-11-03 0.4320 0.011018764 0.4104036 0.4535964
## 37                                                   IBD/TIPP 2016-11-04 0.4420 0.017514599 0.4076720 0.4763280
## 38                                                     YouGov 2016-11-01 0.4600 0.014193655 0.4321809 0.4878191
## 39                                                   IBD/TIPP 2016-10-31 0.4460 0.015579317 0.4154651 0.4765349
## 40                                                      Ipsos 2016-11-02 0.4550 0.011358664 0.4327374 0.4772626
## 41                   Rasmussen Reports/Pulse Opinion Research 2016-11-03 0.4400 0.012816656 0.4148798 0.4651202
## 42                                   The Times-Picayune/Lucid 2016-11-06 0.4500 0.009786814 0.4308182 0.4691818
## 43                                                      Ipsos 2016-11-01 0.4470 0.011810940 0.4238510 0.4701490
## 44                                                   IBD/TIPP 2016-11-02 0.4400 0.016858185 0.4069586 0.4730414
## 45                                                   IBD/TIPP 2016-11-01 0.4400 0.016907006 0.4068629 0.4731371
## 46                   Rasmussen Reports/Pulse Opinion Research 2016-11-02 0.4200 0.012743626 0.3950230 0.4449770
## 47                                                      Ipsos 2016-10-31 0.4400 0.012973281 0.4145728 0.4654272
## 48                                   The Times-Picayune/Lucid 2016-11-05 0.4500 0.009898535 0.4305992 0.4694008
## 49                   Rasmussen Reports/Pulse Opinion Research 2016-10-31 0.4400 0.012816656 0.4148798 0.4651202
## 50                                    Google Consumer Surveys 2016-10-31 0.3769 0.003107749 0.3708089 0.3829911
## 51                                       CVOTER International 2016-11-05 0.4925 0.012609413 0.4677860 0.5172140
## 52                   Rasmussen Reports/Pulse Opinion Research 2016-11-01 0.4400 0.012816656 0.4148798 0.4651202
## 53                                       CVOTER International 2016-11-04 0.4906 0.012998976 0.4651225 0.5160775
## 54                                   The Times-Picayune/Lucid 2016-11-04 0.4500 0.009830663 0.4307323 0.4692677
## 55                                      USC Dornsife/LA Times 2016-11-06 0.4323 0.009144248 0.4143776 0.4502224
## 56                                       CVOTER International 2016-11-03 0.4853 0.013381202 0.4590733 0.5115267
## 57                                   The Times-Picayune/Lucid 2016-11-03 0.4400 0.009684792 0.4210182 0.4589818
## 58                                      USC Dornsife/LA Times 2016-11-05 0.4263 0.009047108 0.4085680 0.4440320
## 59                                       CVOTER International 2016-11-02 0.4878 0.013711286 0.4609264 0.5146736
## 60                                      USC Dornsife/LA Times 2016-11-04 0.4256 0.009046705 0.4078688 0.4433312
## 61                                       CVOTER International 2016-11-01 0.4881 0.013441133 0.4617559 0.5144441
## 62                                   The Times-Picayune/Lucid 2016-11-02 0.4400 0.009697721 0.4209928 0.4590072
## 63                                           Gravis Marketing 2016-10-31 0.4600 0.006807590 0.4466574 0.4733426
## 64                                      USC Dornsife/LA Times 2016-11-03 0.4338 0.009106200 0.4159522 0.4516478
## 65                                   The Times-Picayune/Lucid 2016-11-01 0.4300 0.009677647 0.4110322 0.4489678
## 66                                      USC Dornsife/LA Times 2016-11-02 0.4247 0.009119319 0.4068265 0.4425735
## 67                                           Gravis Marketing 2016-11-02 0.4700 0.010114336 0.4501763 0.4898237
## 68                                      USC Dornsife/LA Times 2016-11-01 0.4236 0.009015504 0.4059299 0.4412701
## 69                                   The Times-Picayune/Lucid 2016-10-31 0.4200 0.009679479 0.4010286 0.4389714
## 70                                      USC Dornsife/LA Times 2016-10-31 0.4328 0.008834895 0.4154839 0.4501161</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>The final tally for the popular vote was Clinton 48.2% and Trump 46.1%. Add a column called <code>hit</code> to <code>pollster_results</code> that states if the confidence interval included the true proportion <span class="math inline">\(p=0.482\)</span> or not. What proportion of confidence intervals included <span class="math inline">\(p\)</span>?</li>
</ol>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="section-3-overview.html#cb72-1" aria-hidden="true"></a><span class="co"># The `pollster_results` object has already been loaded. Examine it using the `head` function.</span></span>
<span id="cb72-2"><a href="section-3-overview.html#cb72-2" aria-hidden="true"></a><span class="kw">head</span>(pollster_results)</span></code></pre></div>
<pre><code>##                                                     pollster    enddate  X_hat      se_hat     lower     upper
## 1                                   ABC News/Washington Post 2016-11-06 0.4700 0.010592790 0.4492385 0.4907615
## 2                                    Google Consumer Surveys 2016-11-07 0.3803 0.002978005 0.3744632 0.3861368
## 3                                                      Ipsos 2016-11-06 0.4200 0.010534681 0.3993524 0.4406476
## 4                                                     YouGov 2016-11-07 0.4500 0.008204286 0.4339199 0.4660801
## 5                                           Gravis Marketing 2016-11-06 0.4700 0.003869218 0.4624165 0.4775835
## 6 Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-06 0.4800 0.013883131 0.4527896 0.5072104</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="section-3-overview.html#cb74-1" aria-hidden="true"></a><span class="co"># Add a logical variable called `hit` that indicates whether the actual value exists within the confidence interval of each poll. Summarize the average `hit` result to determine the proportion of polls with confidence intervals include the actual value. Save the result as an object called `avg_hit`.</span></span>
<span id="cb74-2"><a href="section-3-overview.html#cb74-2" aria-hidden="true"></a>avg_hit &lt;-<span class="st"> </span>pollster_results <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">hit=</span>(lower<span class="op">&lt;</span><span class="fl">0.482</span> <span class="op">&amp;</span><span class="st"> </span>upper<span class="op">&gt;</span><span class="fl">0.482</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="kw">mean</span>(hit))</span>
<span id="cb74-3"><a href="section-3-overview.html#cb74-3" aria-hidden="true"></a>avg_hit</span></code></pre></div>
<pre><code>##   mean(hit)
## 1 0.3142857</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>If these confidence intervals are constructed correctly, and the theory holds up, what proportion of confidence intervals should include <span class="math inline">\(p\)</span>?</li>
</ol>
<ul class="task-list">
<li><input type="checkbox" disabled="" />
A. 0.05</li>
<li><input type="checkbox" disabled="" />
B. 0.31</li>
<li><input type="checkbox" disabled="" />
C. 0.50</li>
<li><input type="checkbox" disabled="" checked="" />
D. 0.95</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>A much smaller proportion of the polls than expected produce confidence intervals containing <span class="math inline">\(p\)</span>.</li>
</ol>
<p>Notice that most polls that fail to include <span class="math inline">\(p\)</span> are underestimating. The rationale for this is that undecided voters historically divide evenly between the two main candidates on election day.</p>
<p>In this case, it is more informative to estimate the spread or the difference between the proportion of two candidates <span class="math inline">\(d\)</span>, or <span class="math inline">\(0.482 − 0.461 = 0.021\)</span> for this election.</p>
<p>Assume that there are only two parties and that <span class="math inline">\(d = 2p − 1\)</span>. Construct a 95% confidence interval for difference in proportions on election night.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="section-3-overview.html#cb76-1" aria-hidden="true"></a><span class="co"># Add a statement to this line of code that will add a new column named `d_hat` to `polls`. The new column should contain the difference in the proportion of voters.</span></span>
<span id="cb76-2"><a href="section-3-overview.html#cb76-2" aria-hidden="true"></a>polls &lt;-<span class="st"> </span>polls_us_election_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(enddate <span class="op">&gt;=</span><span class="st"> &quot;2016-10-31&quot;</span> <span class="op">&amp;</span><span class="st"> </span>state <span class="op">==</span><span class="st"> &quot;U.S.&quot;</span>)  <span class="op">%&gt;%</span></span>
<span id="cb76-3"><a href="section-3-overview.html#cb76-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">d_hat =</span> rawpoll_clinton<span class="op">/</span><span class="dv">100</span> <span class="op">-</span><span class="st"> </span>rawpoll_trump<span class="op">/</span><span class="dv">100</span>)</span>
<span id="cb76-4"><a href="section-3-overview.html#cb76-4" aria-hidden="true"></a></span>
<span id="cb76-5"><a href="section-3-overview.html#cb76-5" aria-hidden="true"></a><span class="co"># Assign the sample size of the first poll in `polls` to a variable called `N`. Print this value to the console.</span></span>
<span id="cb76-6"><a href="section-3-overview.html#cb76-6" aria-hidden="true"></a>N &lt;-<span class="st"> </span>polls<span class="op">$</span>samplesize[<span class="dv">1</span>]</span>
<span id="cb76-7"><a href="section-3-overview.html#cb76-7" aria-hidden="true"></a>N</span></code></pre></div>
<pre><code>## [1] 2220</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="section-3-overview.html#cb78-1" aria-hidden="true"></a><span class="co"># Assign the difference `d_hat` of the first poll in `polls` to a variable called `d_hat`. Print this value to the console.</span></span>
<span id="cb78-2"><a href="section-3-overview.html#cb78-2" aria-hidden="true"></a>d_hat &lt;-<span class="st"> </span>polls<span class="op">$</span>d_hat[<span class="dv">1</span>]</span>
<span id="cb78-3"><a href="section-3-overview.html#cb78-3" aria-hidden="true"></a>d_hat</span></code></pre></div>
<pre><code>## [1] 0.04</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="section-3-overview.html#cb80-1" aria-hidden="true"></a><span class="co"># Assign proportion of votes for Clinton to the variable `X_hat`.</span></span>
<span id="cb80-2"><a href="section-3-overview.html#cb80-2" aria-hidden="true"></a>X_hat &lt;-<span class="st"> </span>(d_hat<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span></span>
<span id="cb80-3"><a href="section-3-overview.html#cb80-3" aria-hidden="true"></a>X_hat</span></code></pre></div>
<pre><code>## [1] 0.52</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="section-3-overview.html#cb82-1" aria-hidden="true"></a><span class="co"># Calculate the standard error of the spread and save it to a variable called `se_hat`. Print this value to the console.</span></span>
<span id="cb82-2"><a href="section-3-overview.html#cb82-2" aria-hidden="true"></a>se_hat &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="kw">sqrt</span>(X_hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>X_hat)<span class="op">/</span>N)</span>
<span id="cb82-3"><a href="section-3-overview.html#cb82-3" aria-hidden="true"></a>se_hat</span></code></pre></div>
<pre><code>## [1] 0.02120683</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="section-3-overview.html#cb84-1" aria-hidden="true"></a><span class="co"># Use `qnorm` to calculate the 95% confidence interval for the difference in the proportions of voters. Save the lower and then the upper confidence interval to a variable called `ci`.</span></span>
<span id="cb84-2"><a href="section-3-overview.html#cb84-2" aria-hidden="true"></a>ci &lt;-<span class="st"> </span><span class="kw">c</span>(d_hat <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat, d_hat <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat)</span>
<span id="cb84-3"><a href="section-3-overview.html#cb84-3" aria-hidden="true"></a>ci</span></code></pre></div>
<pre><code>## [1] -0.001564627  0.081564627</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>Create a new object called <code>pollster_results</code> that contains the pollster’s name, the end date of the poll, the difference in the proportion of voters who declared a vote either, and the lower and upper bounds of the confidence interval for the estimate.</li>
</ol>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="section-3-overview.html#cb86-1" aria-hidden="true"></a><span class="co"># The subset `polls` data with &#39;d_hat&#39; already calculated has been loaded. Examine it using the `head` function.</span></span>
<span id="cb86-2"><a href="section-3-overview.html#cb86-2" aria-hidden="true"></a><span class="kw">head</span>(polls)</span></code></pre></div>
<pre><code>##   state  startdate    enddate                                                   pollster grade samplesize population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin
## 1  U.S. 2016-11-03 2016-11-06                                   ABC News/Washington Post    A+       2220         lv           47.00         43.00            4.00               NA
## 2  U.S. 2016-11-01 2016-11-07                                    Google Consumer Surveys     B      26574         lv           38.03         35.69            5.46               NA
## 3  U.S. 2016-11-02 2016-11-06                                                      Ipsos    A-       2195         lv           42.00         39.00            6.00               NA
## 4  U.S. 2016-11-04 2016-11-07                                                     YouGov     B       3677         lv           45.00         41.00            5.00               NA
## 5  U.S. 2016-11-03 2016-11-06                                           Gravis Marketing    B-      16639         rv           47.00         43.00            3.00               NA
## 6  U.S. 2016-11-03 2016-11-06 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1295         lv           48.00         44.00            3.00               NA
##   adjpoll_clinton adjpoll_trump adjpoll_johnson adjpoll_mcmullin  d_hat
## 1        45.20163      41.72430        4.626221               NA 0.0400
## 2        43.34557      41.21439        5.175792               NA 0.0234
## 3        42.02638      38.81620        6.844734               NA 0.0300
## 4        45.65676      40.92004        6.069454               NA 0.0400
## 5        46.84089      42.33184        3.726098               NA 0.0400
## 6        49.02208      43.95631        3.057876               NA 0.0400</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="section-3-overview.html#cb88-1" aria-hidden="true"></a><span class="co"># Create a new object called `pollster_results` that contains columns for pollster name, end date, d_hat, lower confidence interval of d_hat, and upper confidence interval of d_hat for each poll.</span></span>
<span id="cb88-2"><a href="section-3-overview.html#cb88-2" aria-hidden="true"></a>d_hat =<span class="st"> </span>polls<span class="op">$</span>rawpoll_clinton<span class="op">/</span><span class="dv">100</span> <span class="op">-</span><span class="st"> </span>polls<span class="op">$</span>rawpoll_trump<span class="op">/</span><span class="dv">100</span></span>
<span id="cb88-3"><a href="section-3-overview.html#cb88-3" aria-hidden="true"></a>X_hat =<span class="st"> </span>(d_hat <span class="op">+</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb88-4"><a href="section-3-overview.html#cb88-4" aria-hidden="true"></a>polls &lt;-<span class="st"> </span><span class="kw">mutate</span>(polls, X_hat, <span class="dt">se_hat =</span> <span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(X_hat <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>X_hat) <span class="op">/</span><span class="st"> </span>samplesize), <span class="dt">lower =</span> d_hat <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat, <span class="dt">upper =</span> d_hat <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se_hat)</span>
<span id="cb88-5"><a href="section-3-overview.html#cb88-5" aria-hidden="true"></a>pollster_results &lt;-<span class="st"> </span><span class="kw">select</span>(polls, pollster, enddate, d_hat, lower, upper)</span>
<span id="cb88-6"><a href="section-3-overview.html#cb88-6" aria-hidden="true"></a>pollster_results</span></code></pre></div>
<pre><code>##                                                      pollster    enddate   d_hat        lower         upper
## 1                                    ABC News/Washington Post 2016-11-06  0.0400 -0.001564627  0.0815646272
## 2                                     Google Consumer Surveys 2016-11-07  0.0234  0.011380104  0.0354198955
## 3                                                       Ipsos 2016-11-06  0.0300 -0.011815309  0.0718153088
## 4                                                      YouGov 2016-11-07  0.0400  0.007703641  0.0722963589
## 5                                            Gravis Marketing 2016-11-06  0.0400  0.024817728  0.0551822719
## 6  Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-06  0.0400 -0.014420872  0.0944208716
## 7                                     CBS News/New York Times 2016-11-06  0.0400 -0.011860967  0.0918609675
## 8                                NBC News/Wall Street Journal 2016-11-05  0.0400 -0.014696100  0.0946961005
## 9                                                    IBD/TIPP 2016-11-07 -0.0150 -0.073901373  0.0439013728
## 10                                           Selzer &amp; Company 2016-11-06  0.0300 -0.039307332  0.0993073320
## 11                                          Angus Reid Global 2016-11-04  0.0400 -0.017724837  0.0977248370
## 12                                        Monmouth University 2016-11-06  0.0600 -0.011534270  0.1315342703
## 13                                             Marist College 2016-11-03  0.0100 -0.053923780  0.0739237800
## 14                                   The Times-Picayune/Lucid 2016-11-07  0.0500  0.011013152  0.0889868476
## 15                                      USC Dornsife/LA Times 2016-11-07 -0.0323 -0.068233293  0.0036332933
## 16                      RKM Research and Communications, Inc. 2016-11-05  0.0320 -0.029670864  0.0936708643
## 17                                       CVOTER International 2016-11-06  0.0278 -0.020801931  0.0764019309
## 18                                            Morning Consult 2016-11-05  0.0300 -0.020889533  0.0808895334
## 19                                               SurveyMonkey 2016-11-06  0.0600  0.052615604  0.0673843956
## 20                   Rasmussen Reports/Pulse Opinion Research 2016-11-06  0.0200 -0.030595930  0.0705959303
## 21                                              Insights West 2016-11-07  0.0400 -0.023875814  0.1038758144
## 22                                 RAND (American Life Panel) 2016-11-01  0.0910  0.050024415  0.1319755848
## 23 Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-03  0.0150 -0.043901373  0.0739013728
## 24                                    CBS News/New York Times 2016-11-01  0.0300 -0.034344689  0.0943446886
## 25                                   ABC News/Washington Post 2016-11-05  0.0400 -0.004497495  0.0844974954
## 26                                                      Ipsos 2016-11-04  0.0400 -0.001341759  0.0813417590
## 27                                   ABC News/Washington Post 2016-11-04  0.0500  0.002312496  0.0976875039
## 28                                                     YouGov 2016-11-06  0.0390  0.032254341  0.0457456589
## 29                                                   IBD/TIPP 2016-11-06 -0.0240 -0.085171524  0.0371715236
## 30                                   ABC News/Washington Post 2016-11-03  0.0400 -0.011988727  0.0919887265
## 31                                                   IBD/TIPP 2016-11-03  0.0050 -0.060404028  0.0704040277
## 32                                                   IBD/TIPP 2016-11-05 -0.0100 -0.075220256  0.0552202561
## 33                                   ABC News/Washington Post 2016-11-02  0.0300 -0.027745070  0.0877450695
## 34                                   ABC News/Washington Post 2016-11-01  0.0200 -0.037362198  0.0773621983
## 35                                   ABC News/Washington Post 2016-10-31  0.0000 -0.057008466  0.0570084657
## 36                                                      Ipsos 2016-11-03  0.0490  0.005454535  0.0925454654
## 37                                                   IBD/TIPP 2016-11-04  0.0050 -0.064121736  0.0741217361
## 38                                                     YouGov 2016-11-01  0.0300 -0.025791885  0.0857918847
## 39                                                   IBD/TIPP 2016-10-31  0.0090 -0.052426619  0.0704266191
## 40                                                      Ipsos 2016-11-02  0.0820  0.037443982  0.1265560180
## 41                   Rasmussen Reports/Pulse Opinion Research 2016-11-03  0.0000 -0.050606052  0.0506060525
## 42                                   The Times-Picayune/Lucid 2016-11-06  0.0500  0.011491350  0.0885086495
## 43                                                      Ipsos 2016-11-01  0.0730  0.026563876  0.1194361238
## 44                                                   IBD/TIPP 2016-11-02 -0.0010 -0.067563833  0.0655638334
## 45                                                   IBD/TIPP 2016-11-01 -0.0040 -0.070756104  0.0627561042
## 46                   Rasmussen Reports/Pulse Opinion Research 2016-11-02 -0.0300 -0.080583275  0.0205832746
## 47                                                      Ipsos 2016-10-31  0.0680  0.016894089  0.1191059111
## 48                                   The Times-Picayune/Lucid 2016-11-05  0.0500  0.011051757  0.0889482429
## 49                   Rasmussen Reports/Pulse Opinion Research 2016-10-31  0.0000 -0.050606052  0.0506060525
## 50                                    Google Consumer Surveys 2016-10-31  0.0262  0.013635277  0.0387647229
## 51                                       CVOTER International 2016-11-05  0.0333 -0.016106137  0.0827061365
## 52                   Rasmussen Reports/Pulse Opinion Research 2016-11-01  0.0000 -0.050606052  0.0506060525
## 53                                       CVOTER International 2016-11-04  0.0124 -0.038560140  0.0633601401
## 54                                   The Times-Picayune/Lucid 2016-11-04  0.0600  0.021340150  0.0986598497
## 55                                      USC Dornsife/LA Times 2016-11-06 -0.0475 -0.083637121 -0.0113628793
## 56                                       CVOTER International 2016-11-03  0.0009 -0.051576011  0.0533760106
## 57                                   The Times-Picayune/Lucid 2016-11-03  0.0500  0.011807815  0.0881921851
## 58                                      USC Dornsife/LA Times 2016-11-05 -0.0553 -0.091100799 -0.0194992008
## 59                                       CVOTER International 2016-11-02  0.0056 -0.048162418  0.0593624177
## 60                                      USC Dornsife/LA Times 2016-11-04 -0.0540 -0.089809343 -0.0181906570
## 61                                       CVOTER International 2016-11-01  0.0067 -0.046002019  0.0594020190
## 62                                   The Times-Picayune/Lucid 2016-11-02  0.0500  0.011756829  0.0882431712
## 63                                           Gravis Marketing 2016-10-31  0.0100 -0.016769729  0.0367697294
## 64                                      USC Dornsife/LA Times 2016-11-03 -0.0351 -0.071090499  0.0008904993
## 65                                   The Times-Picayune/Lucid 2016-11-01  0.0300 -0.008295761  0.0682957614
## 66                                      USC Dornsife/LA Times 2016-11-02 -0.0503 -0.086413709 -0.0141862908
## 67                                           Gravis Marketing 2016-11-02  0.0200 -0.019711083  0.0597110831
## 68                                      USC Dornsife/LA Times 2016-11-01 -0.0547 -0.090406512 -0.0189934879
## 69                                   The Times-Picayune/Lucid 2016-10-31  0.0200 -0.018430368  0.0584303678
## 70                                      USC Dornsife/LA Times 2016-10-31 -0.0362 -0.071126335 -0.0012736645</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>What proportion of confidence intervals for the difference between the proportion of voters included <span class="math inline">\(d\)</span>, the actual difference in election day?</li>
</ol>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="section-3-overview.html#cb90-1" aria-hidden="true"></a><span class="co"># The `pollster_results` object has already been loaded. Examine it using the `head` function.</span></span>
<span id="cb90-2"><a href="section-3-overview.html#cb90-2" aria-hidden="true"></a><span class="kw">head</span>(pollster_results)</span></code></pre></div>
<pre><code>##                                                     pollster    enddate  d_hat        lower      upper
## 1                                   ABC News/Washington Post 2016-11-06 0.0400 -0.001564627 0.08156463
## 2                                    Google Consumer Surveys 2016-11-07 0.0234  0.011380104 0.03541990
## 3                                                      Ipsos 2016-11-06 0.0300 -0.011815309 0.07181531
## 4                                                     YouGov 2016-11-07 0.0400  0.007703641 0.07229636
## 5                                           Gravis Marketing 2016-11-06 0.0400  0.024817728 0.05518227
## 6 Fox News/Anderson Robbins Research/Shaw &amp; Company Research 2016-11-06 0.0400 -0.014420872 0.09442087</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="section-3-overview.html#cb92-1" aria-hidden="true"></a><span class="co"># Add a logical variable called `hit` that indicates whether the actual value (0.021) exists within the confidence interval of each poll. Summarize the average `hit` result to determine the proportion of polls with confidence intervals include the actual value. Save the result as an object called `avg_hit`.</span></span>
<span id="cb92-2"><a href="section-3-overview.html#cb92-2" aria-hidden="true"></a>avg_hit &lt;-<span class="st"> </span>pollster_results <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">hit=</span>(lower<span class="op">&lt;</span><span class="fl">0.021</span> <span class="op">&amp;</span><span class="st"> </span>upper<span class="op">&gt;</span><span class="fl">0.021</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="kw">mean</span>(hit))</span>
<span id="cb92-3"><a href="section-3-overview.html#cb92-3" aria-hidden="true"></a>avg_hit</span></code></pre></div>
<pre><code>##   mean(hit)
## 1 0.7714286</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Although the proportion of confidence intervals that include the actual difference between the proportion of voters increases substantially, it is still lower that 0.95.</li>
</ol>
<p>In the next chapter, we learn the reason for this. To motivate our next exercises, calculate the difference between each poll’s estimate <span class="math inline">\(\bar{d}\)</span> and the actual <span class="math inline">\(d = 0.021\)</span>. Stratify this difference, or error, by pollster in a plot.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="section-3-overview.html#cb94-1" aria-hidden="true"></a><span class="co"># The `polls` object has already been loaded. Examine it using the `head` function.</span></span>
<span id="cb94-2"><a href="section-3-overview.html#cb94-2" aria-hidden="true"></a><span class="kw">head</span>(polls)</span></code></pre></div>
<pre><code>##   state  startdate    enddate                                                   pollster grade samplesize population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin
## 1  U.S. 2016-11-03 2016-11-06                                   ABC News/Washington Post    A+       2220         lv           47.00         43.00            4.00               NA
## 2  U.S. 2016-11-01 2016-11-07                                    Google Consumer Surveys     B      26574         lv           38.03         35.69            5.46               NA
## 3  U.S. 2016-11-02 2016-11-06                                                      Ipsos    A-       2195         lv           42.00         39.00            6.00               NA
## 4  U.S. 2016-11-04 2016-11-07                                                     YouGov     B       3677         lv           45.00         41.00            5.00               NA
## 5  U.S. 2016-11-03 2016-11-06                                           Gravis Marketing    B-      16639         rv           47.00         43.00            3.00               NA
## 6  U.S. 2016-11-03 2016-11-06 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1295         lv           48.00         44.00            3.00               NA
##   adjpoll_clinton adjpoll_trump adjpoll_johnson adjpoll_mcmullin  d_hat  X_hat      se_hat        lower      upper
## 1        45.20163      41.72430        4.626221               NA 0.0400 0.5200 0.021206832 -0.001564627 0.08156463
## 2        43.34557      41.21439        5.175792               NA 0.0234 0.5117 0.006132712  0.011380104 0.03541990
## 3        42.02638      38.81620        6.844734               NA 0.0300 0.5150 0.021334733 -0.011815309 0.07181531
## 4        45.65676      40.92004        6.069454               NA 0.0400 0.5200 0.016478037  0.007703641 0.07229636
## 5        46.84089      42.33184        3.726098               NA 0.0400 0.5200 0.007746199  0.024817728 0.05518227
## 6        49.02208      43.95631        3.057876               NA 0.0400 0.5200 0.027766261 -0.014420872 0.09442087</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="section-3-overview.html#cb96-1" aria-hidden="true"></a><span class="co"># Add variable called `error` to the object `polls` that contains the difference between d_hat and the actual difference on election day. Then make a plot of the error stratified by pollster.</span></span>
<span id="cb96-2"><a href="section-3-overview.html#cb96-2" aria-hidden="true"></a>error &lt;-<span class="st"> </span>polls<span class="op">$</span>d_hat <span class="op">-</span><span class="st"> </span><span class="fl">0.021</span></span>
<span id="cb96-3"><a href="section-3-overview.html#cb96-3" aria-hidden="true"></a>polls &lt;-<span class="st"> </span><span class="kw">mutate</span>(polls, error)</span>
<span id="cb96-4"><a href="section-3-overview.html#cb96-4" aria-hidden="true"></a>polls <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> pollster, <span class="dt">y =</span> error)) <span class="op">+</span></span>
<span id="cb96-5"><a href="section-3-overview.html#cb96-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb96-6"><a href="section-3-overview.html#cb96-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="img/figures/unnamed-chunk-32-1.png" width="672" /></p>
<ol start="9" style="list-style-type: decimal">
<li>Remake the plot you made for the previous exercise, but only for pollsters that took five or more polls.</li>
</ol>
<p>You can use dplyr tools <code>group_by</code> and <code>n</code> to group data by a variable of interest and then count the number of observations in the groups. The function <code>filter</code> filters data piped into it by your specified condition.</p>
<p>For example:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="section-3-overview.html#cb97-1" aria-hidden="true"></a>data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(variable_for_grouping) </span>
<span id="cb97-2"><a href="section-3-overview.html#cb97-2" aria-hidden="true"></a>    <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">n</span>() <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span>)</span></code></pre></div>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="section-3-overview.html#cb98-1" aria-hidden="true"></a><span class="co"># The `polls` object has already been loaded. Examine it using the `head` function.</span></span>
<span id="cb98-2"><a href="section-3-overview.html#cb98-2" aria-hidden="true"></a><span class="kw">head</span>(polls)</span></code></pre></div>
<pre><code>##   state  startdate    enddate                                                   pollster grade samplesize population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin
## 1  U.S. 2016-11-03 2016-11-06                                   ABC News/Washington Post    A+       2220         lv           47.00         43.00            4.00               NA
## 2  U.S. 2016-11-01 2016-11-07                                    Google Consumer Surveys     B      26574         lv           38.03         35.69            5.46               NA
## 3  U.S. 2016-11-02 2016-11-06                                                      Ipsos    A-       2195         lv           42.00         39.00            6.00               NA
## 4  U.S. 2016-11-04 2016-11-07                                                     YouGov     B       3677         lv           45.00         41.00            5.00               NA
## 5  U.S. 2016-11-03 2016-11-06                                           Gravis Marketing    B-      16639         rv           47.00         43.00            3.00               NA
## 6  U.S. 2016-11-03 2016-11-06 Fox News/Anderson Robbins Research/Shaw &amp; Company Research     A       1295         lv           48.00         44.00            3.00               NA
##   adjpoll_clinton adjpoll_trump adjpoll_johnson adjpoll_mcmullin  d_hat  X_hat      se_hat        lower      upper  error
## 1        45.20163      41.72430        4.626221               NA 0.0400 0.5200 0.021206832 -0.001564627 0.08156463 0.0190
## 2        43.34557      41.21439        5.175792               NA 0.0234 0.5117 0.006132712  0.011380104 0.03541990 0.0024
## 3        42.02638      38.81620        6.844734               NA 0.0300 0.5150 0.021334733 -0.011815309 0.07181531 0.0090
## 4        45.65676      40.92004        6.069454               NA 0.0400 0.5200 0.016478037  0.007703641 0.07229636 0.0190
## 5        46.84089      42.33184        3.726098               NA 0.0400 0.5200 0.007746199  0.024817728 0.05518227 0.0190
## 6        49.02208      43.95631        3.057876               NA 0.0400 0.5200 0.027766261 -0.014420872 0.09442087 0.0190</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="section-3-overview.html#cb100-1" aria-hidden="true"></a><span class="co"># Add variable called `error` to the object `polls` that contains the difference between d_hat and the actual difference on election day. Then make a plot of the error stratified by pollster, but only for pollsters who took 5 or more polls.</span></span>
<span id="cb100-2"><a href="section-3-overview.html#cb100-2" aria-hidden="true"></a>error &lt;-<span class="st"> </span>polls<span class="op">$</span>d_hat <span class="op">-</span><span class="st"> </span><span class="fl">0.021</span></span>
<span id="cb100-3"><a href="section-3-overview.html#cb100-3" aria-hidden="true"></a>polls &lt;-<span class="st"> </span><span class="kw">mutate</span>(polls, error)</span>
<span id="cb100-4"><a href="section-3-overview.html#cb100-4" aria-hidden="true"></a>polls <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(pollster) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">n</span>() <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span>) </span></code></pre></div>
<pre><code>## # A tibble: 48 x 21
## # Groups:   pollster [7]
##    state startdate  enddate    pollster grade samplesize population rawpoll_clinton rawpoll_trump rawpoll_johnson rawpoll_mcmullin adjpoll_clinton adjpoll_trump adjpoll_johnson
##    &lt;fct&gt; &lt;date&gt;     &lt;date&gt;     &lt;fct&gt;    &lt;fct&gt;      &lt;int&gt; &lt;chr&gt;                &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;
##  1 U.S.  2016-11-03 2016-11-06 ABC New… A+          2220 lv                    47            43               4                 NA            45.2          41.7            4.63
##  2 U.S.  2016-11-02 2016-11-06 Ipsos    A-          2195 lv                    42            39               6                 NA            42.0          38.8            6.84
##  3 U.S.  2016-11-04 2016-11-07 IBD/TIPP A-          1107 lv                    41.2          42.7             7.1               NA            42.9          42.2            6.32
##  4 U.S.  2016-11-05 2016-11-07 The Tim… &lt;NA&gt;        2521 lv                    45            40               5                 NA            45.1          42.3            3.68
##  5 U.S.  2016-11-01 2016-11-07 USC Dor… &lt;NA&gt;        2972 lv                    43.6          46.8            NA                 NA            45.3          43.4           NA   
##  6 U.S.  2016-10-31 2016-11-06 CVOTER … C+          1625 lv                    48.9          46.1            NA                 NA            47.0          42.0           NA   
##  7 U.S.  2016-11-02 2016-11-06 Rasmuss… C+          1500 lv                    45            43               4                 NA            45.6          43.1            4.42
##  8 U.S.  2016-11-02 2016-11-05 ABC New… A+          1937 lv                    47            43               4                 NA            45.3          41.8            4.64
##  9 U.S.  2016-10-31 2016-11-04 Ipsos    A-          2244 lv                    43            39               6                 NA            43.1          39.0            6.76
## 10 U.S.  2016-11-01 2016-11-04 ABC New… A+          1685 lv                    48            43               4                 NA            46.3          41.8            4.62
## # … with 38 more rows, and 7 more variables: adjpoll_mcmullin &lt;dbl&gt;, d_hat &lt;dbl&gt;, X_hat &lt;dbl&gt;, se_hat &lt;dbl&gt;, lower &lt;dbl&gt;, upper &lt;dbl&gt;, error &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="section-3-overview.html#cb102-1" aria-hidden="true"></a>polls <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> pollster, <span class="dt">y =</span> error)) <span class="op">+</span></span>
<span id="cb102-2"><a href="section-3-overview.html#cb102-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb102-3"><a href="section-3-overview.html#cb102-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="img/figures/unnamed-chunk-34-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="section-2-overview.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="section-4-overview.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
